version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
      POSTGRES_DB: liquidity
    
    
  ingest:
    build: ./lp-ingest
    container_name: lp_ingest
    restart: always
    depends_on:
      - postgres
    ports: 
      - "5000:5000"
    environment:
      WAIT_HOSTS: postgres:5432
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./config/badgerdao_ingest.env


  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
      - 50070:50070
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./config/hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    ports:
      - "9864:9864"
      - "50010:50010"
      - "50020:50020"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./config/hadoop.env
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./config/hadoop.env

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./config/hadoop.env
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./config/hadoop.env
  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_SUBMIT_ARGS
    env_file:
      - ./config/hadoop.env
  spark-worker-1:
    image: bde2020/spark-worker:3.0.0-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./config/hadoop.env
  lp-clean:
    build: ./lp-clean
    container_name: lp-clean
    restart: always
    depends_on:
      - spark-master
      - spark-worker-1
    ports:
      - "8083:8083"
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_APPLICATION_PYTHON_LOCATION=/app/clean/lp_clean.py
      - SPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-avro_2.12:2.4.4 --driver-memory 512M 
      - SPARK_APPLICATION_ARGS=--hdfs_path hdfs://namenode:9000/user/root --pool_id 0x3472a5a71965499acd81997a54bba8d852c6e53d
    env_file:
      - ./config/hadoop.env
  lp-load:
    build: ./lp-load
    container_name: lp-load
    restart: always
    depends_on:
      - spark-master
      - spark-worker-1
      - postgres
    ports:
      - "8084:8084"
    environment:
      - SPARK_MASTER_NAME=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_APPLICATION_PYTHON_LOCATION=/app/load/lp_load.py
      - SPARK_SUBMIT_ARGS=--packages org.apache.spark:spark-avro_2.12:2.4.4 --driver-memory 512M --jars /usr/share/java/postgresql-jdbc-42.2.2.jar --driver-class-path /usr/share/java/postgresql-jdbc-42.2.2.jar
      - SPARK_APPLICATION_ARGS=--hdfs_path hdfs://namenode:9000/user/root --pool_id 0x3472a5a71965499acd81997a54bba8d852c6e53d --pg_port 5432 --pg_db liquidity --pg_table public.lqdty_info --pg_user postgres --pg_pwd example
    env_file:
      - ./config/hadoop.env

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
